In [2]:
x=85
y=35
print(x)

85

In [5]:
def greet(name):
    print("hello "+name)
greet("pari")

hello pari

In [ ]:
!pip install pandas numpy matplotlib seaborn

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pari\desktop\learning js\myvnv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\pari\desktop\learning js\myvnv\lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\pari\desktop\learning js\myvnv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 2.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.9 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.9 MB 3.1 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.9 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.5 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 3.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.9 MB 3.5 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 3.6 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.0 MB/s  0:00:03
Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 4.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.4 MB 4.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.4 MB 4.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.4 MB 4.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.4 MB 4.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.4 MB 4.8 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.4 MB 4.6 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.4 MB 4.7 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.4 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 4.6 MB/s  0:00:02
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 2.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.3 MB 3.0 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.3 MB 3.3 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.3 MB 3.0 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.3 MB 2.9 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.3 MB 2.9 MB/s eta 0:00:02
   ---------------------- ----------------- 4.7/8.3 MB 3.1 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.3 MB 3.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.3 MB 3.3 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 7.6/8.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 3.1 MB/s  0:00:02
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ------------------ --------------------- 1.0/2.3 MB 4.7 MB/s eta 0:00:01
   --------------------------- ------------ 1.6/2.3 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 3.5 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.2 MB 1.6 MB/s eta 0:00:04
   ------- -------------------------------- 1.3/7.2 MB 2.0 MB/s eta 0:00:03
   ---------- ----------------------------- 1.8/7.2 MB 2.2 MB/s eta 0:00:03
   ------------- -------------------------- 2.4/7.2 MB 2.4 MB/s eta 0:00:03
   ----------------- ---------------------- 3.1/7.2 MB 2.5 MB/s eta 0:00:02
   ------------------ --------------------- 3.4/7.2 MB 2.5 MB/s eta 0:00:02
   ----------------------- ---------------- 4.2/7.2 MB 2.4 MB/s eta 0:00:02
   -------------------------- ------------- 4.7/7.2 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 5.5/7.2 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 5.8/7.2 MB 2.6 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 2.6 MB/s  0:00:02
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, seaborn

   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   --- ------------------------------------  1/11 [pyparsing]
   --- ------------------------------------  1/11 [pyparsing]
   --- ------------------------------------  1/11 [pyparsing]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]
   ------------------------- --------------  7/11 [pandas]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

In [ ]:
data=pd.read_csv("Clean_Dataset.csv")

In [9]:
data

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [11]:
data.head(9)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954

In [12]:
data.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [13]:
data.shape

(300153, 12)

In [15]:
data.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [16]:
data.airline.value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [17]:
data.airline.unique()

<StringArray>
['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo', 'Air_India']
Length: 6, dtype: str

In [18]:
data.stops.unique()

<StringArray>
['zero', 'one', 'two_or_more']
Length: 3, dtype: str

In [ ]:
data.drop_duplicates()
data.fillna("n/a")
data.dropna()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 27.5 MB